### ISSUE TITLE
Support gRPC stats officially by artillery/artillery

### ISSUE THREAD

**Issue by kenju** [kenju/artillery-engine-grpc#12]
# Problem

artillery/artillery stats is tightly coupled with the http engine

https://github.com/artilleryio/artillery/blob/65a5510b117f1f13054d587627f79095ae40cc0d/core/lib/stats2.js#L154-L168

```js
  result.rps = {
    mean: this.getRate('engine.http.request_rate') || this.getRate('engine.socketio.emit_rate') || this.getRate('engine.websocket.send_rate')
  };

  const ns = this._summaries['engine.http.response_time'] || this._summaries['engine.socketio.response_time'];
```

Therefore, artillery's default stats are useless with gRPC engine like below:

```
Summary report @ 16:33:33(+0900) 2020-03-05
  Scenarios launched:  10
  Scenarios completed: 10
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
```

Although we offer custom metrics for gRPC engine like below, this stats looks broken or useless for library's users.

```
  engine.grpc.response_time:
    min: 49.5
    max: 9360.3
    median: 4753.3
    p95: 9107.1
    p99: 9360.3
  engine.grpc.responses.total: 50
  engine.grpc.responses.success: 50
```

# Solution

- add disable metrics option at artillery/artillery
- make stats calculation logic pluggable at artillery/artillery

**Comment by kenju** [comment]
> Solution

👉 https://github.com/artilleryio/artillery/pull/811

Output stats will look like this (if this PR gets merged)

```
Started phase 0, duration: 10s @ 23:59:59(+0900) 2020-03-05
Time: 00:00:09(+0900) 2020-03-06
Elapsed time: 10 seconds
  scenarios.created.test backend-service running at http://localhost:8000: ............ 9
  scenarios.created.total: ............................................................ 9
  scenarios.failed: ................................................................... 9
  grpc.responses.total: ............................................................... 36
  grpc.responses.success: ............................................................. 27
  grpc.codes.0: ....................................................................... 27
  grpc.responses.error: ............................................................... 9
  grpc.codes.5: ....................................................................... 9
  errors.Error: 5 NOT_FOUND: NOT_FOUND: ............................................... 9
  grpc.response_time:
    min: .............................................................................. 95
    max: .............................................................................. 8513.3
    median: ........................................................................... 4095
    p95: .............................................................................. 8191
    p99: .............................................................................. 8703


Time: 00:00:10(+0900) 2020-03-06
Elapsed time: 10 seconds
  scenarios.created.test backend-service running at http://localhost:8000: ............ 1
  scenarios.created.total: ............................................................ 1
  scenarios.failed: ................................................................... 1
  grpc.responses.total: ............................................................... 4
  grpc.responses.success: ............................................................. 3
  grpc.codes.0: ....................................................................... 3
  grpc.responses.error: ............................................................... 1
  grpc.codes.5: ....................................................................... 1
  errors.Error: 5 NOT_FOUND: NOT_FOUND: ............................................... 1
  grpc.response_time:
    min: .............................................................................. 9050
    max: .............................................................................. 9201.6
    median: ........................................................................... 9215
    p95: .............................................................................. 9215
    p99: .............................................................................. 9215


All virtual users finished
Summary report @ 00:00:10(+0900) 2020-03-06
Total time: 10 seconds
  scenarios.created.test backend-service running at http://localhost:8000: ............ 10
  scenarios.created.total: ............................................................ 10
  scenarios.failed: ................................................................... 10
  grpc.responses.total: ............................................................... 40
  grpc.responses.success: ............................................................. 30
  grpc.codes.0: ....................................................................... 30
  grpc.responses.error: ............................................................... 10
  grpc.codes.5: ....................................................................... 10
  errors.Error: 5 NOT_FOUND: NOT_FOUND: ............................................... 10
  grpc.response_time:
    min: .............................................................................. 92
    max: .............................................................................. 9202.6
    median: ........................................................................... 4351
    p95: .............................................................................. 9215
    p99: .............................................................................. 9215
```
